name: Generate Snake

on:
  schedule: # chạy tự động mỗi ngày lúc 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # cho phép chạy thủ công từ tab Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: tuananh37201
          outputs: dist/snake.svg

      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
